version: '3.9'
services:
  sl-issue-tracker:
    env_file:
      - './.env'
    container_name: 'sl-issue-tracker-backend'
    volumes:
      - sl-issue-tracker_data:/app/store
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    ports:
      - 1928:1928
    links:
      - "postgres:postgres"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.paste.rule=Host(`sl.mingodesk.com`)"
      - "traefik.http.routers.paste.tls.certResolver=letsencrypt-tls"
  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - './.env'
    restart: unless-stopped
    ports:
      - 5432:5432
volumes:
  sl-issue-tracker_data:
  postgres_data: