version: '3.9'
services:
  sl-issue-tracker:
    env_file:
      - './.env'
    container_name: 'sl-issue-tracker-backend'
    volumes:
      - sl-issue-tracker_data:/app/store
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    ports:
      - 1928:1928
    links:
      - "postgres: postgres"
  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - './.env'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: # Set a new user for prod (MUST MATCH WITH THE ONE IN THE .env FILE)
      POSTGRES_PASSWORD: # Set a new password for prod (MUST MATCH WITH THE ONE IN THE .env FILE)
      POSTGRES_DB: sl # The PostgreSQL default database (automatically created at first launch
volumes:
  sl-issue-tracker_data:
  postgres_data: