version: '3.9'
services:
  sl-issue-tracker:
    env_file:
      - './.env'
    container_name: 'sl-issue-tracker-backend'
    volumes:
      - sl-issue-tracker_data:/app/store
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    ports:
      - 1928:1928
    links:
      - "postgres: postgres"
  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    volumes:
      - postgres_data:/postgres/data/db
    env_file:
      - './.env'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: titus # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: GARBAGE_PaSSWORD1 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: sl # The PostgreSQL default database (automatically created at first launch
volumes:
  sl-issue-tracker_data:
  postgres_data: