version: '3.9'
networks:
  default:
    name: 'sl-issue-tracker-databases'
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    volumes:
      - postgres_data:/postgres/data/db
    env_file:
      - './postgres.env'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: titus # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: garbagage_password_please_change # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: sl_fault_tracker # The PostgreSQL default database (automatically created at first launch
volumes:
  postgres_data: